AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SecurityHubInsightSecHubSevOpen001:
    Type: 'AWS::SecurityHub::Insight'
    Properties:
      Name: 'SHMetrics001: Security Hub Findings by Severity'
      Filters:
        ProductName:
          - Comparison: 'EQUALS'
            Value: 'Security Hub'
        WorkflowStatus:
          - Comparison: 'EQUALS'
            Value: 'NEW'
          - Comparison: 'EQUALS'
            Value: 'NOTIFIED'
        RecordState:
          - Comparison: 'EQUALS'
            Value: 'ACTIVE'
      GroupByAttribute: 'SeverityLabel'
  SecurityHubInsightGDSevOpen002:
    Type: 'AWS::SecurityHub::Insight'
    Properties:
      Name: 'SHMetrics002: GuardDuty Findings by Severity'
      Filters:
        ProductName:
          - Comparison: 'EQUALS'
            Value: 'GuardDuty'
        WorkflowStatus:
          - Comparison: 'EQUALS'
            Value: 'NEW'
          - Comparison: 'EQUALS'
            Value: 'NOTIFIED'
        RecordState:
          - Comparison: 'EQUALS'
            Value: 'ACTIVE'
      GroupByAttribute: 'SeverityLabel'
  SecurityHubInsightIAMAASev003:
    Type: 'AWS::SecurityHub::Insight'
    Properties:
      Name: 'SHMetrics003: IAM AA Findings by Severity'
      Filters:
        ProductName:
          - Comparison: 'EQUALS'
            Value: 'IAM Access Analyzer'
        WorkflowStatus:
          - Comparison: 'EQUALS'
            Value: 'NEW'
          - Comparison: 'EQUALS'
            Value: 'NOTIFIED'
        RecordState:
          - Comparison: 'EQUALS'
            Value: 'ACTIVE'
      GroupByAttribute: 'SeverityLabel'
  SecurityHubInsightInspectorSev004:
    Type: 'AWS::SecurityHub::Insight'
    Properties:
      Name: 'SHMetrics004: Inspecor Findings by Severity'
      Filters:
        ProductName:
          - Comparison: 'EQUALS'
            Value: 'Inspector'
        WorkflowStatus:
          - Comparison: 'EQUALS'
            Value: 'NEW'
          - Comparison: 'EQUALS'
            Value: 'NOTIFIED'
        RecordState:
          - Comparison: 'EQUALS'
            Value: 'ACTIVE'
      GroupByAttribute: 'SeverityLabel'
Outputs:
  SecurityHubInsightSecHubSevOpenArn001:
    Value: !Ref SecurityHubInsightSecHubSevOpen001
    Description: 'SHMetrics001: Security Hub Findings by Severity'
  SecurityHubInsightGDSevOpenArn002:
    Value: !Ref SecurityHubInsightGDSevOpen002
    Description: 'SHMetrics002: GuardDuty Findings by Severity'
  SecurityHubInsightIAMAASevArn003:
    Value: !Ref SecurityHubInsightIAMAASev003
    Description: 'SHMetrics003: IAM AA Findings by Severity'
  SecurityHubInsightInspectorSevArn004:
    Value: !Ref SecurityHubInsightInspectorSev004
    Description: 'SHMetrics004: Inspector Findings by Severity'