AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyInsight:
    Type: AWS::SecurityHub::Insight
    Properties:
      Name: 'GuardDuty findings grouped by severity'
      Filters: 
        ProductName:
          - Comparison: EQUALS
            Value: GuardDuty
      
      GroupByAttribute: 'SeverityLabel'
