Resources:
    SHMetricsFunction:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: shmetrics-lambda
            Handler: main.lambda_handler
            Runtime: python3.12
            Role: !GetAtt ShmetricsLambdaRole.Arn
            Code:
                S3Bucket: 193203723632-shmetrics-lambda
                S3Key: deploy/shmetrics-LATEST.zip
            Timeout: 60
            MemorySize: 128
            Environment:
                Variables:
                    CONSOLE_OUTPUT: False
                    CWM_namespace: "shmetrics"
                    CWM_OUTPUT: True
                    CWL_OUTPUT: True
                    CWL_GROUPNAME: "shmetrics"
                    CWL_STREAM: "shmetrics"
                    LOGLEVEL: "INFO"
                    LAMBDA_S3_BUCKET: !ImportValue SHmetricsBucketName
                    LAMBDA_S3_PREFIX: "config"
                    LAMBDA_S3_KEY: "insights.json"
                    SHMETRICS_CONFIG: "insights.json"

    ShmetricsLambdaRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: shmetrics-lambda-role
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: lambda.amazonaws.com
                      Action: sts:AssumeRole
            Policies:
                - PolicyName: shmetrics-s3
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action:
                                - s3:Get*
                            Resource: !ImportValue SHmetricsBucketArn
                - PolicyName: shmetrics-cloudwatch
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action:
                                - cloudwatch:PutMetricData
                                - logs:CreateLogGroup
                                - logs:CreateLogStream
                                - logs:PutLogEvents
                            Resource: '*'
                - PolicyName: shmetrics-lambda
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action:
                                - lambda:InvokeFunction
                            Resource: '*'
                - PolicyName: shmetrics-securityhub
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action:
                                - securityhub:GetInsightResults
                            Resource: '*'

    SHMetricsCronRule:
        Type: AWS::Events::Rule
        Properties:
            Description: "SHMetrics Cron Rule"
            ScheduleExpression: "cron(0 * * * ? *)"
            State: ENABLED
            Targets:
              - Arn: !GetAtt SHMetricsFunction.Arn
                Id: "SHMetricsLambdaTarget"
    SHMetricsCronPermission:
        Type: AWS::Lambda::Permission
        Properties:
            FunctionName: !Ref SHMetricsFunction
            Action: "lambda:InvokeFunction"
            Principal: events.amazonaws.com
            SourceArn: !GetAtt SHMetricsCronRule.Arn
