Resources:
    SHmetricsLambdaDeployBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: 193203723632-shmetrics-lambda
          VersioningConfiguration:
            Status: 'Enabled'
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: 'AES256'
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true

    MyLambdaFunction:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: shmetrics-lambda
            Handler: index.handler
            Runtime: python3.12
            Role: !GetAtt ShmetricsLambdaRole.Arn
            Code:
                S3Bucket: !Ref SHmetricsLambdaDeployBucket
                S3Key: /deploy/shmetrics-LATEST.zip
            Timeout: 60
            MemorySize: 128

    ShmetricsLambdaRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: shmetrics-lambda-role
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: lambda.amazonaws.com
                      Action: sts:AssumeRole
            Policies:
                - PolicyName: shmetrics-s3
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action:
                                - s3:GetObject
                            Resource: !Sub arn:aws:s3:::${SHmetricsLambdaDeployBucket}/*
                - PolicyName: shmetrics-cloudwatch
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action:
                                - cloudwatch:PutMetricData
                                - logs:CreateLogGroup
                                - logs:CreateLogStream
                                - logs:PutLogEvents
                            Resource: '*'
